proto-lens-protoc/proto-lens-protoc.cabal
proto-lens-protoc/src/Bootstrap/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens-protoc/src/Bootstrap/Proto/Google/Protobuf/Descriptor.hs
proto-lens-protoc/src/Generate.hs
proto-lens-tests/tests/enum.proto
proto-lens-tests/tests/enum_test.hs
proto-lens/proto-lens.cabal
proto-lens/src/Data/ProtoLens/Message.hs
proto-lens/src/Data/ProtoLens/Message/Enum.hs

- Add a bounded instance for all proto-lens enums.
- Generate sane 'succ', 'pred' and 'enumFrom*' functions for proto
enums.

Improvements to Enums.

---

ChangeLog.md
proto-lens-arbitrary/proto-lens-arbitrary.cabal
proto-lens-combinators/proto-lens-combinators.cabal
proto-lens-optparse/proto-lens-optparse.cabal
proto-lens-protoc/proto-lens-protoc.cabal
proto-lens-tests/proto-lens-tests.cabal
proto-lens/proto-lens.cabal

Also add a top-level ChangeLog.  (Eventually we may want per-package
changelogs, but let's keep things simple for now.)

Bump versions to 0.1.0.1.

---

proto-lens-combinators/proto-lens-combinators.cabal
proto-lens-protoc/proto-lens-protoc.cabal
proto-lens/proto-lens.cabal
stack.yaml

Relax constraint on data-default-class. Switch resolver to lts-6.20.

---

proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs
stack-bootstrap.yaml

- Add the 'lens-labels' dependency
- Bootstrap against the master on github, rather than a local commit.
- Regenerate the bootstrap files.  The only change is to make all fields
strict (#63).

Update and re-run the bootstrap script.

---

ChangeLog.md
proto-lens-combinators/proto-lens-combinators.cabal
proto-lens-descriptors/proto-lens-descriptors.cabal
proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs
proto-lens-protobuf-types/proto-lens-protobuf-types.cabal
proto-lens-protoc/proto-lens-protoc.cabal
proto-lens/proto-lens.cabal

Also regenerate the bootstrap library and bump its version for consistency.

Bump versions to 0.2.1.0.

---

proto-lens-optparse/proto-lens-optparse.cabal

Flagged in fpco/stackage#2569.

Bump the optparse-applicative dependency.

---

proto-lens-protoc/src/Data/ProtoLens/Setup.hs

Example output when `protoc` is missing:
Configuring proto-lens-protobuf-types-0.2.1.0...
proto-lens-protobuf-types-0.2.1.0: build (lib)
==========
Error: couldn't find the executable "protoc" in your $PATH.
Follow the installation instructions at https://google.github.io/proto-lens/installing-protoc.html .
==========
Missing executable "protoc"
CallStack (from HasCallStack):
error, called at src/Data/ProtoLens/Setup.hs:296:13 in
proto-lens-protoc-0.2.1.0-EdtYegZINjJ3cgy3Ej8Sfv:Data.ProtoLens.Setup

Print a better error message when missing protoc/proto-lens-protoc.

---

.travis.yml
lens-labels/lens-labels.cabal
lens-labels/src/Lens/Labels.hs
proto-lens-arbitrary/proto-lens-arbitrary.cabal
proto-lens-benchmarks/proto-lens-benchmarks.cabal
proto-lens-combinators/proto-lens-combinators.cabal
proto-lens-descriptors/proto-lens-descriptors.cabal
proto-lens-optparse/proto-lens-optparse.cabal
proto-lens-protobuf-types/proto-lens-protobuf-types.cabal
proto-lens-protoc/proto-lens-protoc.cabal
proto-lens-protoc/src/Data/ProtoLens/Setup.hs
proto-lens-tests-dep/proto-lens-tests-dep.cabal
proto-lens-tests/proto-lens-tests.cabal
proto-lens-tests/tests/enum_test.hs
proto-lens/proto-lens.cabal
stack-8.2.1.yaml

Also add `stack-8.2.1.yaml` and track this in Travis CI.

Update to build with gh-8.2.1 and Cabal-2.0.0.2

---

proto-lens/src/Data/ProtoLens/Encoding.hs
proto-lens/src/Data/ProtoLens/Encoding/Wire.hs
proto-lens/src/Data/ProtoLens/Message.hs

Previously we were sometimes using a raw Int.

Use the Tag newtype consistently.

---

lens-labels/Changelog.md
lens-labels/package.yaml
proto-lens-arbitrary/Changelog.md
proto-lens-arbitrary/package.yaml
proto-lens-benchmarks/package.yaml
proto-lens-combinators/Changelog.md
proto-lens-combinators/package.yaml
proto-lens-optparse/Changelog.md
proto-lens-optparse/package.yaml
proto-lens-protobuf-types/Changelog.md
proto-lens-protobuf-types/package.yaml
proto-lens-protoc/Changelog.md
proto-lens-protoc/package.yaml
proto-lens-tests-dep/package.yaml
proto-lens-tests/package.yaml
proto-lens/Changelog.md
proto-lens/package.yaml

Also updates a couple missing entries in the changelog.
Fixes #122.

Bump package version numbers and tweak changelogs.

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/164)

Update format links

---

.travis.yml
stack.yaml

Also use that in CI instead of an earlier nightly build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/169)

Bump the resolver to `lts-10.3` (ghc-8.2.2).

---

proto-lens-protoc/Changelog.md
proto-lens-protoc/package.yaml
proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs

Tested with `stack test --resolver=nightly-2018-01-15`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/170)

Build with `haskell-src-exts-1.20.*`.

---

proto-lens-optparse/Changelog.md
proto-lens-optparse/package.yaml
proto-lens-optparse/src/Data/ProtoLens/Optparse.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/181)

Add MessageEnum ReadM and option builders.

---

README.md
TYPES.md
docs/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/204)

Scalar type refs

---

proto-lens-combinators/Changelog.md
proto-lens-protobuf-types/Changelog.md
proto-lens-protoc/Changelog.md

For:
- proto-lens-protoc-0.3.1.1
- proto-lens-protobuf-types-0.3.0.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/209)

Update changelogs for next 0.3.* release.

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/215)

Fix a bug in CI that ignored the result of `stack test`.

---

.travis.yml
proto-lens/Changelog.md
proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs
proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
proto-lens/src/Proto/Google/Protobuf/Descriptor_Fields.hs

Updates both the git submodule and Travis CI.
Also reruns bootstrap to update the descriptor protos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/217)

Bump to protobuf-3.6.1.

---

lens-labels/Changelog.md
lens-labels/package.yaml
proto-lens-protobuf-types/Changelog.md
proto-lens-protobuf-types/package.yaml
proto-lens-protoc/Changelog.md
proto-lens-runtime/Changelog.md
proto-lens-runtime/package.yaml
proto-lens/Changelog.md
proto-lens/package.yaml

We made a breaking change in #208.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/219)

Bump the version of lens-labels.

---

proto-lens-protoc/Changelog.md
proto-lens/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/223)

Fix a couple typos.

---

README.md

As noted in #226.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/227)

Fix link to types.md.

---

proto-lens-tutorial/person/README.md

Fix #233.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/234)

Import defMessage consistently

---

.travis.yml
discrimination-ieee754/package.yaml
lens-labels/package.yaml
proto-lens-arbitrary/package.yaml
proto-lens-combinators/package.yaml
proto-lens-discrimination/package.yaml
proto-lens-optparse/package.yaml
proto-lens-protobuf-types/package.yaml
proto-lens-protoc/package.yaml
proto-lens-runtime/package.yaml
proto-lens-setup/package.yaml
proto-lens-setup/src/Data/ProtoLens/Setup.hs
proto-lens-tests/package.yaml
proto-lens-tutorial/stack-ghc-8.6.yaml
proto-lens/package.yaml
stack-ghc-8.6.yaml
stack.yaml

Add a separate stack config YAML since not everything builds yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/242)

Build with ghc-8.6.1 using Stackage nightly.

---

proto-lens-arbitrary/Changelog.md
proto-lens-arbitrary/package.yaml
proto-lens-combinators/Changelog.md
proto-lens-combinators/package.yaml
proto-lens-optparse/Changelog.md
proto-lens-protobuf-types/Changelog.md
proto-lens-protobuf-types/package.yaml
proto-lens-protoc/Changelog.md
proto-lens-protoc/package.yaml
proto-lens-setup/Changelog.md
proto-lens-setup/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/244)

Update version numbers and changelogs for a minor release.

---

lens-labels/Changelog.md
lens-labels/package.yaml
proto-lens/Changelog.md
proto-lens/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/246)

Bump the versions of proto-lens and lens-labels.

---

proto-lens-optparse/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/247)

Actually bump the version of proto-lens-optparse.

---

proto-lens/src/Data/ProtoLens/Encoding.hs

Hi all. While benchmarking my gRPC code I found out a few easy-to-squash hot-spots in proto-lens. This patch earns a bit of speed (5%-ish in benchmarks) by convincing GHC to INLINE a bit further.
Results of stack bench on my dev machine:
At master `de9ce30`: [bench.noinline.txt](https://github.com/google/proto-lens/files/2569232/bench.noinline.txt)
At `2bb76c7`: [bench.inlined.txt](https://github.com/google/proto-lens/files/2569234/bench.inlined.txt)
Next, I'd like to investigate some other tweaks such as specializing `integralFieldWireType` for all the combinations that can happen in proto3. But I'll need to be a bit more familiar with proto-lens internals. Then I can have a longer pass trying to spot improvements here and there.
---
This change is [<img …

Inline utility functions and strictify FieldWireType.

---

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/284)

Generate encodings for oneof fields.

---

proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs

This will let us experiment with its implementation without
changing the external API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/294)

Expose Parser as an opaque type.

---

.travis.yml
proto-lens/package.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/295)

Clean up the generated-encoding flag, which is now unused.

---

proto-lens/Changelog.md

I missed adding this to a previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/296)

Update the proto-lens Changelog.

---

stack-ghc-8.6.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/299)

Switch from nightly to lts-13.1.

---

proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs

They are available on ghc-4.11 (8.4) and newer
(despite what the comment says, they weren't released in 8.2):
https://github.com/ghc/ghc/blob/1c9dab22f010352884d6f7e5b62251bc4b0cca7c/libraries/base/GHC/Float.hs#L1323
In addition to simplifying our code, this speeds up the float benchmarks.
When rebased onto #302, it provides further speedups:
float-packed(4003B)/encode: 12.29 μs => 7.347 μs
float-packed(4003B)/decode/whnf: 11.13 μs => 4.623 μs
float-unpacked(5000B)/encode 20.5 μs => 17.13 μs
float-unpacked(5000B)/decode/whnf 10.83 μs => 10.90 μs
It's still not great that we're doing the cast per-element, but this
seems like an easy win over something more complicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Use built-in casts from float/double<->word32/word64.

---

lens-labels/Changelog.md
lens-labels/package.yaml
proto-lens-arbitrary/Changelog.md
proto-lens-arbitrary/package.yaml
proto-lens-discrimination/package.yaml
proto-lens-optparse/Changelog.md
proto-lens-optparse/package.yaml
proto-lens-protobuf-types/Changelog.md
proto-lens-protobuf-types/package.yaml
proto-lens-protoc/Changelog.md
proto-lens-protoc/package.yaml
proto-lens-runtime/Changelog.md
proto-lens-runtime/package.yaml
proto-lens-setup/Changelog.md
proto-lens-setup/package.yaml
proto-lens/Changelog.md
proto-lens/package.yaml

Also reorganize the changelogs to emphasize which changes are breaking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/308)

Update changelogs and versions for a new release.

---

.travis.yml
docs/installing-protoc.md

Latest version released is v3.7.1

Updating protoc version

---

.travis.yml

This looks like the bug we're running into:
https://gitlab.haskell.org/ghc/ghc/issues/14051

Fix CI by bumping to ghc-8.2.2.

---

stack-bootstrap.yaml

Switch stack-bootstrap.yaml to the newer stack extra-deps syntax.

---

proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs
proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
proto-lens/src/Proto/Google/Protobuf/Descriptor_Fields.hs

There's a couple internal changes this adds back, which should help
improve diffs in later CLs.  There's no external API change.

Regenerate the bootstrap protos.

---

docs/index.md
docs/reserved-names.md
docs/types.md

Also adding some minor format fix

Adding list of reserved keywords for field names.

---

.travis.yml
discrimination-ieee754/package.yaml
proto-lens-discrimination/package.yaml
proto-lens-discrimination/src/Data/ProtoLens/Discrimination.hs
proto-lens-discrimination/src/Data/ProtoLens/Group.hs
proto-lens-discrimination/src/Data/ProtoLens/Sort.hs
proto-lens-discrimination/tests/disc_test.hs
proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs

Okay, this time fix the underlying issue instead of suppressing the warning

Changes to work with lts-15.2

---

proto-lens-tutorial/coffee-order/README.md

Corrected the link to the order.proto in the readme of the coffee-order tutorial

Update Coffee-order tutorial README.md

---

proto-lens-arbitrary/Changelog.md
proto-lens-arbitrary/package.yaml
proto-lens-optparse/Changelog.md
proto-lens-optparse/package.yaml
proto-lens-protobuf-types/Changelog.md
proto-lens-protoc/Changelog.md
proto-lens-runtime/Changelog.md
proto-lens-setup/Changelog.md
proto-lens-setup/package.yaml
proto-lens/Changelog.md

Update changelogs and bump the versions wherever needed.
This is related to https://github.com/google/proto-lens/issues/381.

Prepare for new version publish

---

proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin.hs
proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs
proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor.hs
proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor_Fields.hs

I worked around #391 by making the bootstrap script use the in-tree packages instead of a separate git checkout, as described here:
https://github.com/google/proto-lens/issues/391#issuecomment-638580806

Regenerate the bootstrap files.

---

proto-lens-protobuf-types/src/Data/ProtoLens/Descriptor.hs
proto-lens-protoc/app/Data/ProtoLens/Compiler/Definitions.hs
proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs
proto-lens-tests/tests/service_test.hs
proto-lens/src/Data/ProtoLens/Service/Types.hs

This is similar to generated messageDescriptor in #361.

Add ServiceDescriptor to generated services.

---

discrimination-ieee754/discrimination-ieee754.cabal
discrimination-ieee754/package.yaml
proto-lens-discrimination/package.yaml
proto-lens-discrimination/proto-lens-discrimination.cabal
proto-lens-discrimination/src/Data/ProtoLens/Group.hs
proto-lens-discrimination/src/Data/ProtoLens/Sort.hs
proto-lens-protobuf-types/package.yaml
proto-lens-protobuf-types/proto-lens-protobuf-types.cabal
stack-9.2.yaml

Add protobuf struct
