google/proto-lens

proto-lens/proto-lens.cabal
You need to use "." to get a line break in the package description field.
=> Fix package description markup.

proto-lens-combinators/proto-lens-combinators.cabal, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Generate.hs, proto-lens-tests/proto-lens-tests.cabal
This should prevent user packages from accidentally depending on
the particular set of modules that we reexport.  For example,
previously they could get the module 'Data.ByteString' from
proto-lens-protoc.  After this change, they'll need to explicitly
list 'bytestring' in their 'build-depends' to get that.
=> Reexport modules with new names from proto-lens-protoc.

proto-lens-protoc/src/Definitions.hs, proto-lens-protoc/src/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/enum.proto, proto-lens-tests/tests/enum_test.hs
The first case listed in the proto for each int value is the "real" enum
constructor, and subsequent ones are synonyms.  This is the same approach as
Java:
https://developers.google.com/protocol-buffers/docs/reference/java-generated#enum
=> Support enum aliases using PatternSynonyms.

proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Plugin.hs, proto-lens-protoc/src/protoc-gen-haskell.hs
This also refactors the main environment analysis a bit so it can be reused, and changes a few functions to accept/return String rather than ModuleName since the un-annotated haskell-src-exts API is on the way out.
=> Move some parts of protoc-gen-haskell to visible modules for use by plugins.

proto-lens-benchmarks/LICENSE, proto-lens-benchmarks/Setup.hs, proto-lens-benchmarks/benchmarks/IntPacking.hs, proto-lens-benchmarks/benchmarks/Nested.hs, proto-lens-benchmarks/benchmarks/UnusedFields.hs, proto-lens-benchmarks/benchmarks/int_packing.proto, proto-lens-benchmarks/benchmarks/nested.proto, proto-lens-benchmarks/benchmarks/unused_fields.proto, proto-lens-benchmarks/proto-lens-benchmarks.cabal, proto-lens-benchmarks/src/Data/ProtoLens/BenchmarkUtil.hs, stack-8.0.yaml, stack.yaml, travis-cabal.sh
This begins to address #24. I didn't really know which benchmarks were important, so I included a small set of benchmarks that were interesting to me. It should be easy for others to add their own based on these examples and using the small BenchmarkUtil library I included. Or I am always happy to add additional benchmarks to this pull request based on review comments.
=> Add proto-lens-benchmarks package with a small set of Criterion benchmarks

.travis.yml, stack-7.10.yaml, stack.yaml
Previously the default was ghc-7.10.3 (lts-6.20), and we built with ghc-8 using an old nightly lts.
Now:
- stack.yaml uses lts-7.4 to build with ghc-8.0.1.
- stack-7.10.3 uses lts-6.22 to build with ghc-7.10.3.
=> Reorganize LTS versions now that ghc-8.0.1 is out of nightly.

README.md, proto-lens/src/Data/ProtoLens/Encoding.hs
While using proto-lens for a side project I took note of a few minor issues I ran into:
- The quick start instructions result in broken packages due to missing setup-depends.
- The Haddock of encodeMessage is ambiguous about which ByteString it returns.
=> Miscellaneous documentation improvements.

proto-lens-protoc/src/Data/ProtoLens/Setup.hs
Also add generatingSpecficProtos.
These functions allow easily using this package to generate haskell
source for specific .proto files in Setup.hs
=> Add defaultMainGeneratingSpecficProtos

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/canonical.proto, proto-lens-tests/tests/text_format.proto, proto-lens-tests/tests/text_format_test.hs, proto-lens/src/Data/ProtoLens/Message.hs, proto-lens/src/Data/ProtoLens/TextFormat.hs
Also split out text_format_test's .proto file rather than sharing it
with canonical_test.
Also changed the "field name" stored in Data.ProtoLens.Message.FieldDescriptor
to be the name of that type, which is more consistent with how TextFormat
prints/parses such messages.
Note: PR #48 previously referenced this bug, but it looks like that was a
typo since that fix was for string escaping, not field ordering.
=> Fix #40 (print fields ordered by tag number).

bootstrap.hs, proto-lens-descriptors/LICENSE, proto-lens-descriptors/Setup.hs, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Plugin.hs, proto-lens-protoc/src/protoc-gen-haskell.hs, stack-7.10.yaml, stack-bootstrap.yaml, stack.yaml, travis-cabal.sh
- Make a new package 'proto-lens-descriptors' for the descriptors
- Name those modules "Proto.*" instead of "Bootstrap.Proto.*"
- Add special logic so the descriptors modules don't use the reexported
modules from proto-lens-protoc (otherwise we'd get a circular dependency)
- Make the bootstrapping script use a special stack YAML file.
=> Make the bootstrapping process more robust:

bootstrap.hs, proto-lens-protoc/proto-lens-protoc.cabal
- Completely hide all library fields of proto-lens-protoc when only building
the executable.  In particular, the `build-depends` packages may change
between versions of the library, and otherwise stack would still try to
resolve them.
- Do a full clean before and after running the bootstrapping script.  Stack
doesn't seem robust enough to handle all edge cases, and I frequently had to
do manual 'stack clean's in order to get things to work.
=> Make bootstrapping more robust:

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/group_test.hs, proto-lens/src/Data/ProtoLens/Encoding.hs, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Wire.hs
Motivated by #58, it turned out there were a few space leaks in the decoder:
- Made all message fields strict
- Add bang patterns to the decoding code
- Don't generate an intermediate list of TaggedValues.
These changes had the happy side effect of significantly speeding up our
decoding benchmarks.  Additionally the "decode/whnf" and "decode/nf" tests now
take the same amount of time, indicating that we do fully force the messages.
|                                              |              before  |                after |
| -------------------------------------------- | -------------------- | -------------------- |
|nested:flat(68kB)/encode                      |  3.547ms (+/- 0.009) |  2.559ms (+/- 0.003) |
|nested:flat(68kB)/decode/whnf                 | 16.304ms (+/- 0.295) | …
=> Improve space usage and time of decoding.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/tests/packed_test.hs, proto-lens-tests/tests/proto3.proto, proto-lens-tests/tests/proto3_test.hs, proto-lens/src/Data/ProtoLens/Encoding.hs
- Don't emit empty packed fields during encoding.
- Allow parsing packed fields as unpacked and vice versa.
- Proto3 repeated fields are packed by default.
=> Fix the handling of packed repeated fields (#38).

proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Plugin.hs, proto-lens-protoc/src/protoc-gen-haskell.hs
Adapted from PR #59 by @expipiplus1.
This is the first step to building `proto-lens` with both older and newer versions of
`haskell-src-exts`, and thus thus getting proto-lens into stackage nightly.
This switches to `haskell-src-exts<=1.17`'s `Language.Haskell.Exts.Annotated.*`
API, which corresponds to `haskell-src-exts>=1.18`'s
`Language.Haskell.Exts.*` .  Annoyingly, every datatype in the new API is
parametrized by a type, which is just `()` in our case.  To simplify the
codegen modules, I moved more functionality into the `Combinators` module and exposed
an API similar to what we had before.
Along the way, I also fixed a bug in the codegenerated error messages.  I
re-ran the bootstrap script to make sure no other changes were introduced.
The next PR will wrap the imports in CPP …
=> Use the "Annotated" API from haskell-src-exts-1.17.*.

ChangeLog.md, lens-labels/lens-labels.cabal, proto-lens-arbitrary/proto-lens-arbitrary.cabal, proto-lens-benchmarks/proto-lens-benchmarks.cabal, proto-lens-combinators/proto-lens-combinators.cabal, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-optparse/proto-lens-optparse.cabal, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-tests/proto-lens-tests.cabal, proto-lens/proto-lens.cabal
I didn't bother changing the versions of proto-lens-benchmarks and
proto-lens-tests since we're not uploading them to Hackage.
Changed the maintainer to proto-lens@googlegroups.com.
=> Update library versions and changelog, and change the maintainer.

proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs
This makes their treatment a little more consistent with other modules,
and allows `proto-lens-protoc` to be self-sufficient as a build-depends
(for example, in proto-only packages such as `proto-lens-protobuf-types`).
=> Include `base`'s modules in the reexport list.

proto-lens-protobuf-types/LICENSE, proto-lens-protobuf-types/Setup.hs, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal, proto-lens-protobuf-types/proto-src, proto-lens-protoc/src/Data/ProtoLens/Setup.hs, proto-lens-tests-dep/LICENSE, proto-lens-tests-dep/Setup.hs, proto-lens-tests-dep/proto-lens-tests-dep.cabal, proto-lens-tests-dep/protos/test-dep/foo.proto, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/package-deps.proto, proto-lens-tests/tests/package-deps_test.hs, stack.yaml, travis-cabal.sh
Also adds the `proto-lens-protobuf-types` package which includes
`Proto.Google.Protobuf.{Any,Duration,Wrappers}`.
This change allows one Haskell package to generate bindings for `foo.proto`,
and another package to generate bindings for `bar.proto`, where
`bar.proto` imports `foo.proto`.
Under the hood, each package copies its `.proto` files into
`$datadir/proto-lens-imports`, so that other packages can find
and use them when compiling their own `.proto` files.
Note: a minor corner case is not handled correctly: if a test or
benchmark requires va .proto that imports from another package,
the *library* also needs to specify that dependency.  See
`proto-lens-tests.cabal` for more details.
=> Allow .proto files to import between Haskell packages.

proto-lens-arbitrary/proto-lens-arbitrary.cabal
Tested by manually editing `stack.yaml`, specifying the new versions in its `extra-deps`.  All tests passed.
=> Bump proto-lens-arbitrary to support newer QuickCheck.

README.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/oneof.proto, proto-lens-tests/tests/oneof_test.hs, proto-lens-tests/tests/proto3.proto, proto-lens-tests/tests/proto3_test.hs
This uses an intermediate sum type encoding for `oneof` fields. The generated lenses don't expose the sum type but rather point directly to (`Maybe`) the underlying type.
See (#21).
=> Sum types for oneof fields

ChangeLog.md, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal, proto-lens-protobuf-types/src/Data/ProtoLens/Any.hs, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/any.proto, proto-lens-tests/tests/any_test.hs, proto-lens-tests/tests/proto3_test.hs, proto-lens/proto-lens.cabal, proto-lens/src/Data/ProtoLens/Message.hs
Fixes #22.
Provides simple `pack` and `unpack` functions.  Since the `unpack` operation
is partial (and has multiple types of "failure"), I wasn't sure how to fit it
into a `Lens`; so I left that alone for the time being.
I turned this into a minor version bump.  It does add a new field to
`MessageDescriptor` which usually requires a major bump; but since that field
is internal to codegen, it shouldn't break any individual users.
=> Add Data.ProtoLens.Any for storing arbitrary Messages.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/oneof.proto, proto-lens-tests/tests/oneof_test.hs
Resolves #21.
Also refactors (again) the logic around codegen for fields and oneofs, as a follow-up
to #85 which created that sum type in the first place.  (In part, it reverts
code structure to an earlier version of that PR.)
Suppose we have
message Foo {
oneof bar {
int32 a = 1;
int64 b = 2;
}
}
Then we'll generate data types:
data Foo { _Foo'bar :: Maybe Foo'Bar }
data Foo'Bar = Foo'A Int32 | Foo'B Int64
(Note: this changes from the previous behavior which called it Foo'bar; the
capitalization/camelcasing feels more appropriate since it's a datatype.)
and overloaded versions of the following lenses:
maybe'bar :: Lens' Foo (Maybe Foo'Bar)
a         :: Lens' Foo Int32
maybe'a   :: Lens' Foo (Maybe Int32)
b         :: Lens' Foo Int64
maybe'b   :: Lens' Foo (Maybe Int64)
The `maybe'bar` …
=> Add a lens for internal "oneof" sum types.

proto-lens-arbitrary/proto-lens-arbitrary.cabal, proto-lens-arbitrary/src/Data/ProtoLens/Arbitrary.hs
Bumps the version to proto-lens-arbitrary-0.1.1.0.
It's fairly useful on its own for anywhere you want a
`Gen MyProtoMessage`; for example, when defining your own
custom `Arbitrary` instances for types that contain protobufs.
Also use `arbitraryMessage/shrinkMessage` a little more directly
in the internal implementation.
=> Export the `arbitraryMessage` function.

bootstrap.hs
The bootstrap yaml file uses a different stack LTS than `stack.yaml`.  So run
`setup` explicitly at the start, even before running any `stack clean`
commands (which also depend on it for some reason).
=> Run `stack setup` in the bootstrap script.

bootstrap.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/enum.proto, proto-lens-tests/tests/enum_test.hs
This PR adds `deriving (Ord)` to all generated data types (messages, oneofs, enums).
The diff is bigger than I'd expect; presumably due to some previous change not having its bootstrap run.
=> Generate Ord instances for all exported datatypes

proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests/tests/names.proto, proto-lens-tests/tests/names_test.hs
Fixes some corner cases: previously underlines (snake_case) were preserved in
message types and oneof types and field constructors.  Instead, we should
camel case everything consistently.
=> CamelCase messages and oneof fields/types.

proto-lens-protoc/proto-lens-protoc.cabal
It will most likely be in the next stack LTS.
Tested by manually editing `stack.yaml` to depend on that version.
=> Bump dependency to haskell-src-exts-0.19.

lens-labels/Changelog.md, lens-labels/lens-labels.cabal, proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/proto-lens-arbitrary.cabal, proto-lens-combinators/Changelog.md, proto-lens-combinators/proto-lens-combinators.cabal, proto-lens-descriptors/Changelog.md, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-optparse/Changelog.md, proto-lens-optparse/proto-lens-optparse.cabal, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal, proto-lens-protoc/Changelog.md, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens/Changelog.md, proto-lens/proto-lens.cabal
Previously we had a top-level file that tracked all the packages.  However,
their versions are drifting; packages like `proto-lens-arbitrary` only need
minor version bumps, while `proto-lens`/`proto-lens-protoc` need major bumps.
Additionally, I'd like to relax the dependencies between `proto-lens`,
`proto-lens-protoc` and `proto-lens-descriptors`.  So it makes sense to start
tracking everything separately.
=> Add individual Changelogs for all the packages.

.travis.yml
Our current build setup for ghc-8.2.1 causes dependencies to be installed
"locally" under `$PWD/.stack-work` rather than `$HOME/.stack` (which is
where snapshot packages are usually stored).  As a result, they weren't being
cached, and the build was taking much longer to complete.
This changes `.travis.yml` so that for the 8.2.1 build, we also cache
everything under `.stack-work`.  It's a little too aggressive since it also
caches the packages in this repo (`proto-lens-*`) which can lead to confusing
false positive build successes if we hit edge cases in stack.  So I'll plan to
revert this once we switch to a Stack LTS that contains ghc-8.2.1.
=> Improve caching for ghc-8.2.1.

lens-labels/Changelog.md, lens-labels/lens-labels.cabal, proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/proto-lens-arbitrary.cabal, proto-lens-combinators/Changelog.md, proto-lens-combinators/proto-lens-combinators.cabal, proto-lens-optparse/Changelog.md, proto-lens-optparse/proto-lens-optparse.cabal
`proto-lens,descriptors,protoc,protobuf-types` will get bumped in another PR.
=> Bump versions of some of the packages.

proto-lens-descriptors/Changelog.md, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal, proto-lens-protoc/Changelog.md, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens/Changelog.md
- Update the changelogs (including updated changes to `proto-lens-protoc`).
- Make `proto-lens`, `proto-lens-descriptors` and `proto-lens-protobuf-types`
depend on `0.2.2.*` rather than `0.2.2.0`.  That should make it easier
to make bugfix package releases without updating all three packages in
lockstep.
=> Prepare for releasing proto-lens-0.2.2.0.

.travis.yml, proto-lens-benchmarks/benchmarks/IntPacking.hs, proto-lens-benchmarks/benchmarks/Nested.hs, proto-lens-benchmarks/benchmarks/UnusedFields.hs, proto-lens-benchmarks/proto-lens-benchmarks.cabal
Looks like these have been broken for a while.
- Make sure to build the individual benchmark programs in Travis CI.
- Track the API changes related to adding `lens-labels`.
=> Fix benchmarks and improve test coverage.

proto-lens-protoc/Changelog.md, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests/tests/oneof.proto, proto-lens-tests/tests/oneof_test.hs
Also bumped `proto-lens-protoc` to `0.2.2.1` in preparation for a bugfix
release.  (The other packages are unchanged.)
The build of `tensorflow/haskell` was breaking with `proto-lens-0.2.2.0`.
Specifically, in `meta_graph.proto`:
message CollectionDef {
message NodeList {...}
oneof kind {
NodeList node_list = 1;
...
}
}
We were using the name `CollectionDef'NodeList` for both the constructor
of the submessage and the constructor of the oneof:
data CollectionDef'NodeList = CollectionDef'NodeList{...}
data CollectionDef'Kind = CollectionDef'NodeList NodeList
| ...
It turns out there's several ways the oneof's names can overlap with message
or enum names; I listed them out in `oneof_test.proto`.
This PR fixes the ambiguity by behaving similarly to the go bindings: …
=> Fix an ambiguity between the names oneof and submessages/subenums.

proto-lens-protoc/Changelog.md, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests/tests/names.proto, proto-lens-tests/tests/names_test.hs
In proto-lens-protoc-0.2.2.0 we added logic to camel-case message names.
Unfortunately, that behavior turned out to be buggy; in particular, `FOOBar`
was turned into `Foobar`.  Additionally, it was inconsistent with enum names
which aren't camel-cased.
Note: we *are* still camel-casing and capitalizing the datatypes and
constructors that are generated for oneof fields.  However, the message part
is unchanged; for example, `message Foo_bar { oneof baz_a {..}}` turns into
`Foo_bar'BazA`.
In a future release we may try to improve the behavior again.  I added unit
tests to help future validation.
=> Don't camel-case message names.

lens-labels/src/Lens/Labels.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin'Fields.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor'Fields.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs
- Swaps the order of type arguments to `HasLens` in order
to make the instances more readable in Haddock and error
messages.
- Adds a new class `HasLens'` which is effectively the
"monomorphic" version of `HasLens`; that is, for lenses of
monomorphic types (which includes all proto messages).
For example:
instance (HasLens' f Foo x a, a ~ b) => HasLens f Foo Foo x a b where
where lensOf = lensOf'
instance Functor f => HasLens' f Foo "a" Int where ...
instance Functor f => HasLens' f Foo "b" Double where ...
instance Functor f => HasLens' f Foo "c" [Float]  where ...
...
And for a polymorphic type:
instance Functor f => HasLens f (a,b) (a,c) "snd" b c where
lensOf _ = lens snd (\(x,_) y -> (x,y))
=> Improve readability of HasLens instances.

README.md
Originally it was only needed for bootstrapping, but now it's also needed
to build `proto-lens-protobuf-types`.
=> Document the submodule command for proto-lens.

proto-lens-descriptors/data/proto-lens-imports/google, proto-lens-descriptors/proto-lens-descriptors.cabal, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/imports.proto
Packages that use Data.ProtoLens.Setup (e.g. proto-lens-protobuf-types) pass
`.proto` file to each other by copying them into
`$datadir/proto-lens-imports/**/*.proto`.  We need to fake this behavior for
`proto-lens-descriptors` since it uses bootstrapping.  So instead
we symlink the `.proto` files manually into the right location.
=> Allow other packages to import protos from proto-lens-descriptors.

proto-lens/src/Data/ProtoLens/Encoding.hs
I double-checked that the Core output is identical before/after
with both `-O` and `-O2`.
=> Define `over'` to make the laziness avoidance more readable.

proto-lens-arbitrary/src/Data/ProtoLens/Arbitrary.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-descriptors/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/src/foo/bar.proto, proto-lens-tests/tests/oneof_test.hs, proto-lens-tests/tests/raw_fields_test.hs, proto-lens-tests/tests/unknown_fields.proto, proto-lens-tests/tests/unknown_fields_test.hs, proto-lens/proto-lens.cabal, proto-lens/src/Data/ProtoLens/Encoding.hs, proto-lens/src/Data/ProtoLens/Encoding/Wire.hs, proto-lens/src/Data/ProtoLens/Message.hs, proto-lens/src/Data/ProtoLens/TextFormat.hs
- Every message has a new field containing a list of unknown fields:
```unknownFields :: Message msg => Lens' msg [TaggedValue]```
- Unknown fields are preserved by `decodeMessage`, `encodeMessage`,
and `showMessage`
- Unknown fields still cause an error for `readMessage`.
A few TODOs:
- For now, unknown groups are printed sub-optimally by `showMessage`: the
start/end group tags (and everything in between) all get displayed as
individual fields, rather than being organized into a sub-struct.
- The `discardUnknownFields` function isn't recursive, unlike in other
languages.
- The Ord instance doesn't try to do anything special, just treating
the unknown fields as a list of values.  If it really matters then
`discardUnknownFields` can help resolve the ambiguity.
=> Add support for tracking unknown fields.

lens-labels/src/Lens/Labels.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/imports.proto, proto-lens-tests/tests/imports_test.hs
Also, minor changes to `lens-labels`:
- Export a `Lens'` type synonym
- Swap the order of `view` to match other packages.
Originally, `imports.proto` and its dependencies were compiled automatically
along with everything in the `tests` folder.  However, we changed the behavior
in #126 to ignore proto files that aren't actually being used in some Cabal
component.
Fixed by adding an explicit test for that file.
=> Add an explicit test for `imports.proto`.

README.md
The regular method `stack ghci <package>` doesn't always work
(or sometimes succeeds but doesn't load all of the autogenerated
proto files).  This change documents a decent workaround that I
managed to find (i.e. `stack exec ghci --package <package>`).
The trick is that using `--package <package>` first builds the package
like normal, and then loads the (compiled) package into ghci.  It's a little
indirect, but seemed to work well enough in my tests.
=> Add notes for a `stack ghci` workaround.

proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/src/Data/ProtoLens/Arbitrary.hs, proto-lens-protoc/Changelog.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens/Changelog.md, proto-lens/src/Data/ProtoLens/Encoding.hs, proto-lens/src/Data/ProtoLens/Message.hs, proto-lens/src/Data/ProtoLens/TextFormat.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
Distinguish the recursive sub-message case from the other
scalar field types.
Motivated by the changes in #134.
Small behaivor change: this prevents any message type from being
packed, not just groups.  (But that's closer to the standard anyway.)
=> Refactor `FieldTypeDescriptor`.

proto-lens/src/Data/ProtoLens/TextFormat.hs, proto-lens/src/Data/ProtoLens/TextFormat/Parser.hs
- Include field names in type mismatch errors
- Quote field names in error messages
Example new output:
```
*** Exception: readMessageOrDie: Error parsing field "value": Type
mismatch: (BytesField,IntValue 3)
```
Compare to old output:
```
*** Exception: readMessageOrDie: Type mismatch: (BytesField,IntValue 3)
```
=> Improve text format error messages.

lens-labels/Changelog.md, lens-labels/package.yaml, lens-labels/src/Lens/Labels.hs, lens-labels/src/Lens/Labels/Unwrapped.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/unwrapped_test.hs
This adds an orphan instance allowing protolens-generated labels to be used in function position.
Duplicate PR to bypass the Travis spam filter.
cc @judah
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/157)
=> Add function instance for IsLabel

proto-lens-arbitrary/src/Data/ProtoLens/Arbitrary.hs
This makes it easier to call `forAllShrink`, which is what you're stuck with if you forego QuickCheck's TH property discovery. Currently this is only accessible via the `ArbitraryMessage` newtype.
Before:
```haskell
forAllShrink arbitraryMessage (fmap unArbitraryMessage . shrink . ArbitraryMessage)
```
After:
```haskell
forAllShrink arbitraryMessage shrinkMessage
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/159)
=> Expose shrinkMessage

proto-lens-protobuf-types/package.yaml
Fix #165. I also have functions for Timestamp <-> UTCTime conversion lying around but was unsure whether they should be in this repo and under which package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/166)
=> Add protobuf timestamp support

lens-labels/Changelog.md, proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens/Changelog.md
Also:
- Loosen the bound for `proto-lens-protoc`'s dependency on `proto-lens`.
Previously it was overly tight to let the `Message` evolve,
but we can be more lenient now that the class is more stable.
- Give `proto-lens-arbitrary` a minor bump to `0.1.2.0` since it added
a function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/168)
=> Update changelogs with some missing entries.

proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs
Now that we define our own `Module` type (#172), we don't need `getModuleName`
to return a `Maybe`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/173)
=> Simplify an API slightly.

proto-lens/Changelog.md, proto-lens/src/Data/ProtoLens/Encoding.hs, proto-lens/src/Data/ProtoLens/Encoding/Wire.hs
Previously, when decoding failed we didn't print the message type, and often
didn't print the field name either.
(Running the benchmarks indicated that this change doesn't noticeably affect
performance; all differences were within noise levels.)
Example of new error message:
```
Left "canonical.Test3 > c: Failed reading: canonical.Test1 > a: Failed
reading: Expected wire type 0 but found 2"
```
where a `Test5` is incorrectly decoded as a `Test3`:
```
message Test1 {
required int32 a = 1;
}
message Test3 {
required Test1 c = 1;
}
message Test2 {
required string b = 1;
}
message Test4 {
required Test2 c = 1;
}
```
I haven't been able to figure out a way to remove the nested "Failed reading"
messages that are added automatically by `attoparsec` without significantly
refactoring the decoding …
=> Improve references to types/fields in error messages.

.travis.yml, lens-labels/Changelog.md, lens-labels/package.yaml, proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml, proto-lens-benchmarks/package.yaml, proto-lens-combinators/Changelog.md, proto-lens-combinators/package.yaml, proto-lens-optparse/Changelog.md, proto-lens-optparse/package.yaml, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests-dep/package.yaml, proto-lens-tests/package.yaml, proto-lens-tutorial/stack.yaml, proto-lens/Changelog.md, proto-lens/package.yaml, proto-lens/src/Data/ProtoLens/Message.hs, proto-lens/src/Data/ProtoLens/TextFormat.hs, stack.yaml
- Bump resolver to lts-11.6 (ghc-8.2.2)
- Add a CI build against nightly stackage
- Bump package versions and update changelogs
The only nontrivial bit was that `Data.Semigroup` is now included
in `base`, and a superclass of `Data.Monoid`.
I also removed all the version bounds from
`proto-lens-{benchmarks,tests,tests-dep}`.  They're mainly noise since we
don't release those packages on Hackage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/191)
=> Get proto-lens building with ghc-8.4.2.

discrimination-ieee754/package.yaml, lens-labels/Changelog.md, lens-labels/package.yaml, proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml, proto-lens-combinators/Changelog.md, proto-lens-combinators/package.yaml, proto-lens-discrimination/package.yaml, proto-lens-optparse/Changelog.md, proto-lens-optparse/package.yaml, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens/Changelog.md, proto-lens/package.yaml
The bump was actually supposed to be done by #136.  Unfortunately,
I accidentally reverted it during the switch to `hpack` (#138).
Also bump package versions and update changelogs accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/197)
=> Bump lower-bounds to `base-4.9`.

proto-lens-protobuf-types/package.yaml, proto-lens-protobuf-types/src/Data/ProtoLens/Any.hs
It's not necessary for the internal code to use the `_Fields` modules,
since proto-lens already requires `ghc>=8.0`.
Additionally, this makes it easier to build `proto-lens-proto-types`
with `rules_haskell`, which doesn't currently generate the `_Fields`
modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/198)
=> Use OverloadedLabels inside Data.ProtoLens.Any.

proto-lens-tutorial/coffee-order/README.md
Looks like the previous versions of the README had broken hyperlinks from a previous branch. This commit changes them to be relative paths so they "shouldn't" break in future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/201)
=> Correct hyperlinks in person tutorial

proto-lens-protobuf-types/package.yaml
We've found it useful to use that generic type, for example in RPCs that don't
return a value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/206)
=> Expose bindings for empty.proto.

lens-labels/src/Lens/Labels.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor_Fields.hs
One of proto-lens's biggest usability issues is the readability (or lack
thereof) of type error messages and type instances. We can improve things
somewhat by drastically simplifying the class we use for overloading labels.
The original version was made to be as general as possible, but no one's ever
used that generality in practice.
Before:
```
class HasLens (f :: * -> *) s t (x :: Symbol) a b where
lensOf :: Proxy# x -> LensLike f s t x a b
```
to
```
class HasLens' s (x :: Symbol) a where
lensOf' :: Functor f => Proxy# x -> LensLike' f s x a
```
This makes two simplifications:
1. Force all lenses to be "monomorphic" by making `s ~ t` and `a ~ b`.
2. Fix these to be real lenses (using `Functor`) rather than generalizing over
`f` to support, say, traversals (which would require …
=> Simplify lens-label instances.

.travis.yml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Setup.hs, proto-lens-tutorial/stack.yaml, stack-bootstrap.yaml, stack.yaml
Also update `stack.yaml` to `lts-12.6` rather than a nightly.
The proto-lens-protoc-0.3.1.1 release had an upper bound
on `temporary` that was too restrictive.  Increase it,
and bump the version to `0.3.1.2`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/211)
=> Fix build of proto-lens-0.3.* on lts-12.

proto-lens-benchmarks/benchmarks/IntPacking.hs, proto-lens-benchmarks/benchmarks/Nested.hs, proto-lens-benchmarks/benchmarks/UnusedFields.hs, proto-lens-protoc/Changelog.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-runtime/package.yaml, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
This helps work around the lack of `Generic` instances (#167) and removes
orphan instances in the benchmarks.
The instances are manually generated for each type, rather than going
via the MessageDescriptor.  This is both for performance (e.g. the benchmarks
use them) and because the MessageDescriptor contains redundant fields (e.g. the
maybe and non-maybe variants of a field).
I examined a couple files for the output of `-ddump-simpl` from `-O` and found
the result was well-optimized, didn't have redundant `seq`s, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/207)
=> Generate explicit instances of NFData.

proto-lens-runtime/Changelog.md, proto-lens-runtime/package.yaml
It was missed in #210.
Also bump proto-lens-runtime to 0.4.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/222)
=> Remove an obsolete dependency on data-default-class.

README.md
- Services are now supported.
- It's now part of the standard to preserve unknown values in proto3:
https://developers.google.com/protocol-buffers/docs/proto3#unknowns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/225)
=> Update the list of differences from the standard.

.travis.yml, stack.yaml
This makes local `stack build` fail if there's a warning.  Previously,
it only failed when run in CI.  (The current version of Stack handles
`ghc-options` much better than when we first set up this project's config.)
(This does not affect the behavior of the Hackage releases.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/240)
=> Set -Wall -Werror in stack.yaml.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs
It diverged significantly over time and had a bunch of duplicate code.
Most of it can be shared, with just omitting the code around the unknown
enum case in proto2 (which doesn't have it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/239)
=> Unify the codegen for proto2 and proto3 enums.

proto-lens-runtime/Changelog.md, proto-lens-runtime/package.yaml
It was already at 0.4.0.1, so it bumps to 0.4.0.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/245)
=> Update version and changelog for proto-lens-runtime.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests/tests/names.proto, proto-lens-tests/tests/names_test.hs
An attempt to fix https://github.com/google/proto-lens/issues/199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/238)
=> Change enum generation to prevent invalid names

proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml
Verified by editing stack.yaml with:
```
extra-deps:
...
- QuickCheck-2.12.6.1
- test-framework-quickcheck2-0.3.0.5
allow-newer: True
```
This will let proto-lens-arbitrary stay in Stackage nightly when
QuickCheck gets bumped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/253)
=> Bump the upper bound on QuickCheck.

lens-labels/src/Lens/Labels.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
Adds an overlapping instance of `HasField` which gives
a better error message when no instance can be found.
Compare these results to:
https://gist.github.com/judah/e6678257cc28f2c486a631e49db885f2#file-lens-errors-md
New error message for the expression
`def & value .~ 3 :: DescriptorProto` :
```
<interactive>:6:14: error:
• Type DescriptorProto has no field named "value"
• In the first argument of ‘(.~)’, namely ‘#value’
In the second argument of ‘(&)’, namely ‘#value .~ "hello"’
In the expression:
defMessage & #value .~ "hello" :: DescriptorProto
```
New error message for the expression `() & #name .~ "hello"`:
```
<interactive>:6:6: error:
• Type () has no field named "name"
• In the first argument of ‘(.~)’, namely ‘#name’
In the second argument of ‘(&)’, namely ‘#name .~ "hello"’
In …
```
=> Use TypeError to improve type error messages.

proto-lens-arbitrary/src/Data/ProtoLens/Arbitrary.hs, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs
Before, shrinkMessage on a map with default key or value could return the
input unchanged, causing QuickCheck to loop forever.
In map.proto:
```
syntax = "proto2";
message Foo {
map<int32, string> bar = 1;
}
```
Shrinking a message can return itself:
```
> mapM_ print $ shrinkMessage (defMessage & bar .~ fromList [(0,"")]  :: Foo)
{}
{bar { key: 0 value: "" }}
{bar { key: 0 value: "" }}
```
After this change, such values are filtered out:
```
mapM_ print $ shrinkMessage (defMessage & bar .~ fromList [(0,"")]  :: Foo)
{}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/252)
=> Fix a bug in shrinkMessage for maps.

.travis.yml, proto-lens-benchmarks/src/Data/ProtoLens/BenchmarkUtil.hs, proto-lens-optparse/package.yaml, proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs
Lets us remove support for lts-8 (ghc-8.0.1), including some
CPP directives for older haskell-src-exts and optparse-applicative.
For bookkeeping I increased the lower bound on optparse-applicative
in proto-lens-optparse, even though technically we didn't lose
support for older versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/272)
=> Bump the lowest supported LTS to lts-8 (ghc-8.0.2).

proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs
Bump the lower bound to support `haskell-src-exts-1.21.0`, adding a CPP
directive to work around an API change.  Tested manually by adding that package
to the Stack `extra-deps`.
Tested by adding `haskell-src-exts-1.21.0` to the `extra-deps` in `stack.yaml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/271)
=> Support haskell-src-exts-1.21.

proto-lens-protoc/Changelog.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-tests/tests/names.proto, proto-lens-tests/tests/names_test.hs
This makes two changes:
1. Previously, we capitalized the names of messages and enums,
but not enum values.  This makes enum values capitalized.
(Fixes #152.)
2. Previously, we didn't capitalize sub-enums the same way we did
submessages; e.g.:
```message Foo {
message bar {}
enum baz {}
```
would be turned into `Foo'Bar` but `Foo'baz`.  This changes
it to `Foo'Baz` for consistency.  (It does the same thing
for values of sub-enums.)
For example, here are the generated Haskell names:
```
message superEnum {      // SuperEnum
enumValue = 1;        // EnumValue
}
message super {          // Super
message subMessage {}  // Super'SubMessage
enum subEnum {         // Super'SubEnum
enumValue = 1;       // Super'EnumValue
}
};
```
---
This change is [<img …
=> Consistently capitalize type names.

proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs
This change consolidates some logic by moving it into the Definitions
module.  In particular, all decisions related to proto2/proto3 are now
contained in that module, including:
- Whether an enum should have an "unknown" case
- Whether a field is repeated/required/optional
This change should help the autogenerated encodings code avoid repeated work
from what's already been implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/269)
=> Refactor some field-related code generation logic.

proto-lens-benchmarks/benchmarks/IntPacking.hs, proto-lens-benchmarks/src/Data/ProtoLens/BenchmarkUtil.hs
Also rearrange the int-packing benchmark so the bar graph looks a little
better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/274)
=>  Benchmark the reflected and generated encodings against each other.

proto-lens/src/Data/ProtoLens/Encoding.hs, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Reflected.hs, proto-lens/src/Data/ProtoLens/Encoding/Reflected/Wire.hs, proto-lens/src/Data/ProtoLens/Message.hs
This will make it easier to replace the parser with something else,
especially as we work on generated encodings.  See also #62.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/276)
=> Move more code and types into Data.ProtoLens.Encoding.Bytes.

proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Reflected/Wire.hs
Previously they were implemented by a loop that didn't optimize well.
This speeds up the benchmark from #277 (decoding repeated floats, reflected)
by a factor of 2.6x.  Specifically, the `float-packed/decode` and `float-unpacked/decode` benchmarks dropped from ~225us to ~85us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/278)
=> Make specialized parsers for `Word32` and `Word64`.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/required.proto, proto-lens-tests/tests/required_test.hs
For each required field, adds a new `Bool` argument to the main loop.
When the loop is finished, it checks that all of the fields are set.
Also adds a unit test checking that we report *all* names of missing
required fields, not just the first one that we find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/288)
=> Check for required fields in the generated parser.

proto-lens-benchmarks/benchmarks/Nested.hs
Lowering the default size from 10k to 100 elements.  Some benchmarks
that looked identical under the old one are 2x different under the new
one.  That indicates the size was causing the benchmark to obscure
some of the overhead.  And since we already have the packing benchmark
to measure the effects of repeated fields, I think it's better for this one to
isolate other effects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/291)
=> Lower the default size of the nested benchmark.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs
Tracks behavior that's already done in the reflected parser (#187).
The benchmarks run about 5% slower after this change.  Given our other
known performance issues (e.g., use of Attoparsec itself, better handling
of packed fields) I think this is a reasonable tradeoff and can be revisited
later if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/289)
=> Include message/field names in generated error messages.

proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/any_test.hs
Previously some tests were relying on pattern match in do bindings;
when they failed, the error messages gave no information about
the problematic value.
I added a `satisfy` function (inspired by some other testing
frameworks) and used it in a few places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/292)
=> Use a `satisfy` function to Improve some test error messages.

proto-lens-benchmarks/benchmarks/Packing.hs
Typos in #277; the benchmark names and proto types didn't match up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/297)
=> Fix incorrect types in the packing benchmark.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/FieldEncoding.hs, proto-lens/package.yaml, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser.hs, proto-lens/tests/parser_test.hs
All decoding benchmarks show significant speedups after this change.
The biggest improvement is to decoding packed data which is 4-5x as fast
as before.  (See below for a full list of benchmark diffs.)
This parsing monad follows the approach of, e.g., the `store` and `persist`
packages.  It requires that all data be in a *strict* `ByteString`,
and uses simple pointer arithmetic internally to walk through its bytes.
This effectively works against #62 (streaming parsers) since it
needs to read all the input data before starting the parse.  However,
that issue has already existed since the beginning of this library for,
e.g., submessages; see that bug for more details.  So this change
doesn't appear to be a regression.  We also have freedom to later
try out different implementations without …
=> Use a custom parsing monad instead of attoparsec.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs
It's a duplicate of `let'`, whose name is more consistent with
`do'`, `case'`, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/300)
=> Remove the redundant `letE` function.

proto-lens-benchmarks/benchmarks/Packing.hs, proto-lens-benchmarks/benchmarks/packing.proto
When decoding/encoding floats, we read a fixed-length Word32
and then "cast" it to a `Float`.  This new benchmark helps separate
the cost of reading/writing that `Word32` from the cost of the
cast itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/301)
=> Add a benchmark for fixed32-packed/unpacked (Word32).

proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs
Further improvements over #303.  The standard functions from
`Data.ByteString.Builder` aren't strict enough and miss some potential
unwrapping opportunities.
Benchmarks (on top of the `internal-vectors` branch):
float-packed(4003B)/encode: 7.346 μs => 3.652 μs
float-unpacked(5000B)/encode: 17.13 μs => 12.64 μs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/304)
=> Make putFixed{32,64} more strict, speeding up encoding of floats.

proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Field.hs, proto-lens-runtime/Changelog.md, proto-lens-runtime/package.yaml, proto-lens-tests/package.yaml, proto-lens-tests/tests/repeated_test.hs, proto-lens/Changelog.md, proto-lens/package.yaml, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Growing.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser/Internal.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser/Unsafe.hs, proto-lens/src/Data/ProtoLens/Message.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor_Fields.hs, proto-lens/tests/growing_test.hs
Fixes #58.
For every repeated field `foo`, add a new lens `vector'foo`
whose field type is a `Vector` instead of a list.  Internally,
repeated fields are always stored as `Vectors`, whether or not
the field is actually packed.  Specifically:
- `Data.Vector.Unboxed.Vector` if the field's Haskell representation is
fixed-length (`Int32`, `Float`, etc.), or
- `Data.Vector.Vector` (i.e., boxed) otherwise (`Text`, `ByteString`, messages,
etc).
For backwards compatibility, the name `foo` continues to be used
for a list and is implemented as
foo = vector'foo . iso Vector.toList Vector.fromList
The generated encoding/decoding code uses those `vector'*` lenses
internally.  For parsing, we keep a separate mutable vector for each
repeated field and grow it manually using the …
=> Store repeated fields as Vectors.

proto-lens/src/Data/ProtoLens/Encoding/Parser.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser/Internal.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser/Unsafe.hs
Previously it was `ExceptT String IO (ParseResult a)`, which is equivalent
to `IO (Either String (ParseResult a))`.  Elide that nested
type into a single datatype:
```
data ParseResult a = ParseSuccess {...} | ParseFailure String
```
Provides ~10% speedup for some benchmarks.  (Less for those
with a packed, fixed-length field.)  Was also suggested to
make the code more clear.
Results, on top of the other pending PRs:
flat(602B)/decode/whnf         8.238 μs => 7.684 μs
nested(900B)/decode/whnf       11.25 μs => 10.67 μs
int32-packed(1003B)/decode/whnf 7.651 μs => 6.697 μs
int32-unpacked(2000B)/decode/whnf 13.30 μs => 11.43 μs
fixed32-packed(4003B)/decode/whnf 2.531 μs => 2.530 μs
fixed32-unpacked(5000B)/decode/whnf 9.264 μs => 8.477 μs
float-packed(4003B)/decode/whnf 4.460 μs => 4.371 μs …
=>  Simplify the Parser monad implementation.

proto-lens-protoc/Changelog.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens/Changelog.md, proto-lens/src/Data/ProtoLens/Field.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
This reverts commit 60b7c3cd8b8dac9e6138b3c2324df9d8e49629ca.
It turned out that the TypeError would sometimes fire incorrectly,
even when there was transitive instance available.  Details:
https://github.com/google/proto-lens/commit/4bb77a571dbccb43b657e6e52ace34eaa422a705
I suspect a GHC bug, but wasn't easily able to simplify the example enough to know
for sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/310)
=> Revert "Use TypeError to improve type error messages. (#265)"

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens/src/Data/ProtoLens/Field.hs, proto-lens/src/Data/ProtoLens/Labels.hs, proto-lens/src/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs
It's more consistent with the class name `HasField` and the helper function `field`.
This is diffbase'd on #265.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/proto-lens/311)
=> Rename `lensOf` to `fieldOf`, for consistency.

proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml
Also bump proto-lens-arbitrary's version number and changelog.
Tested by adding the new version to `stack-ghc-8.6.yaml`, and
running:
```
$ stack test --resolver lts-13.15 --stack-yaml=stack-ghc-8.6.yaml
```
=> Bump the upper bound on QuickCheck to 2.13.

proto-lens-protoc/Changelog.md, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/tests/names.proto, proto-lens-tests/tests/names_test.hs
In general, protoc doesn't allow message types and enum values to be the same.
However, since we change the case of enum values, it's possible for us
to produce an overlap.  (For example, a message called "Job" and an enum value
called "job").
I fixed it by changing the name of the message constructor, which is an internal detail
not exposed by our API.
=> Fix a naming conflict between message constructors and enum values.

proto-lens-tests/tests/text_format_test.hs, proto-lens/src/Data/ProtoLens/TextFormat/Parser.hs
It's valid for text format protobufs to contain strings with unescaped quote
characters different from the characters used to delimit the string.
=> Fix a bug in text format parsing

proto-lens/Changelog.md, proto-lens/package.yaml
Also update the version and changelog to prepare for another release.
=> Bump the upper bound on profunctors to allow 5.4.

docs/installing-protoc.md
Also unzip `include/` folder into `usr/local/include` to make sure plugins that commonly requires them works immediately.
=> In `protoc` install commands, also extract `include/`

proto-lens/Changelog.md, proto-lens/package.yaml
Tested via `stack test` with the following (local) `stack.yaml` changes: added newer versions of `vector` and `vector-algorithms`, and commented out the dicrimination packages since the released version doesn't build yet with `primitive-0.7`.  (Which should be irrelevant for this PR which is only about the `proto-lens` package.)
```
resolver: lts-12.7
packages:
-- discrimination-ieee754
+#- discrimination-ieee754
- proto-lens
- proto-lens-arbitrary
-- proto-lens-discrimination
+#- proto-lens-discrimination
- proto-lens-optparse
- proto-lens-protobuf-types
- proto-lens-protoc
@@ -14,8 +14,11 @@ packages:
- proto-lens-tests
- proto-lens-tests-dep
extra-deps:
-- discrimination-0.3
+#- discrimination-0.3
- promises-0.3
+- primitive-0.7.0.0
+- vector-0.12.0.3
+- vector-algorithms-0.8.0.1
```
=> Allow primitive-0.7.

proto-lens/Changelog.md, proto-lens/package.yaml
We need a minor version bump due to adding a new function
(`decodeMessageDelimitedH`).
=> Bump proto-lens to 0.5.1.0 and update the Changelog.

README.md, proto-lens-protoc/Changelog.md, proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Plugin.hs, proto-lens-tests/tests/imports_test.hs
Fixes #19.
After this change, if `bar.proto` contains the line
import public foo.proto
Then it turns into
```
module Proto.Bar(..., module Proto.Foo) where
import Proto.Foo  -- unqualified, to allow the reexport of its definitions
```
The previous hacky approach was: `Proto.Bar` doesn't reexport `Proto.Foo`;
instead, if another file `baz.proto` imports `bar.proto`, *then* the codegen
of `Proto.Baz` imports `Proto.Foo` as well as `Proto.Bar`.  This approach
let us avoid module-level exports, but had two limitations:
1) It violated the principle of "strict dependencies", since `Proto.Baz`
is importing what is essentially a transitive dependency.
2) Non-codegen modules that import a proto module can't benefit from
`import public` statements.
=> Properly implement `import public`.

proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/empty.proto, proto-lens-tests/tests/imports_dep.proto
Previously, if we reexported an empty module, we ran into `-Wdodgy-imports`.
In practice, this came up because of a proto file that only defined an
extension, which proto-lens doesn't support yet, so it generated an
empty module.
I think proto-lens-protoc's architecture makes it nontrivial to detect whether a module
has no exports.  So I just suppressed the `-Wdodgy-imports` warning.  I also
converted the other warnings from `-fno-warn-*` to `-Wno-*` for consistency,
since GHC has supported that form for a while.
=> Prevent warnings for "import public" on an empty .proto file.

proto-lens-tests/package.yaml, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/any_test.hs, proto-lens-tests/tests/canonical_test.hs, proto-lens-tests/tests/combinators_test.hs, proto-lens-tests/tests/decode_delimited_test.hs, proto-lens-tests/tests/dependent_test.hs, proto-lens-tests/tests/enum_test.hs, proto-lens-tests/tests/group_test.hs, proto-lens-tests/tests/imports_test.hs, proto-lens-tests/tests/labels_test.hs, proto-lens-tests/tests/names_test.hs, proto-lens-tests/tests/no_package_test.hs, proto-lens-tests/tests/oneof_test.hs, proto-lens-tests/tests/optional_test.hs, proto-lens-tests/tests/package-deps_test.hs, proto-lens-tests/tests/proto3_test.hs, proto-lens-tests/tests/raw_fields_test.hs, proto-lens-tests/tests/repeated_test.hs, proto-lens-tests/tests/required_test.hs, proto-lens-tests/tests/service_test.hs, proto-lens-tests/tests/text_format_test.hs, proto-lens-tests/tests/unknown_fields_test.hs, proto-lens/package.yaml, proto-lens/tests/growing_test.hs, proto-lens/tests/parser_test.hs
test-framework isn't in Stackage nightly, in part due to
its dependency regex-posix not yet building with ghc-8.8.
test-framework also doesn't seem to be as actively developed
anymore.
Luckily, the translation was fairly mechanical.
=> Switch from test-framework to tasty.

docs/installing-protoc.md
This tended to work with bash before because it ignores globs
that don't expand to anything.  But it failed in zsh with
the error `no matches found: include/*`.
Fixes #346
=> Properly quote a glob in the install command.

proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/tests/service.proto, proto-lens-tests/tests/service_test.hs, proto-lens/Changelog.md, proto-lens/src/Data/ProtoLens/Service/Types.hs, proto-lens/src/Proto/Google/Protobuf/Descriptor.hs-boot
We're not using it currently.  Also, the existing approach
doesn't work well with our internal Blaze rules.  If we still
want this long-term, we can revisit it after fixing #334.
=> Revert #331 and remove `methodOptions`.

proto-lens-protoc/package.yaml, proto-lens-tutorial/stack-ghc-8.6.yaml, proto-lens-tutorial/stack-nightly.yaml, proto-lens-tutorial/stack.yaml, stack-bootstrap.yaml, stack-nightly.yaml, stack.yaml
We need it for RPCs with a single method, which require
google/ghc-source-gen#55.
Also remove an old stack-ghc-8.6.yaml file that isn't used anymore.
=> Bump the ghc-source-gen dependency to 0.3.0.0.

.travis.yml, README.md, cabal.project, proto-lens-discrimination/package.yaml, proto-lens-protobuf-types/package.yaml, proto-lens-tests-dep/package.yaml, proto-lens-tests/package.yaml, proto-lens-tutorial/coffee-order/package.yaml, proto-lens-tutorial/person/package.yaml, travis-cabal-new.sh, travis-cabal.sh
- Make all the .cabal files explicitly declare
`build-tool-depends: proto-lens-protoc:proto-lens-protoc`.
Also bump hpack to support that syntax.
- Use `generated-exposed-modules` and `generated-other-modules`
consistently.
For now, Travis just has a single case (8.6.5).  Switching
completely is be blocked on #354 (including .protos from deps).
=> Support cabal new-build, and add a Travis case.

bootstrap.hs, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor_Fields.hs, proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-protoc/package.yaml, proto-lens-tests/package.yaml, proto-lens/Changelog.md, stack-bootstrap.yaml
Previously the checked-in bootstrap protos were part of the proto-lens package.
After this change, they're included in the `other-modules` of
proto-lens-protoc`.  Instead, the exposed versions of the modules are
provided by proto-lens-protobuf-types, just like the other proto
files.
Fixed #344, which describes why this was causing issues with some
build systems like Bazel.
Another side effect of this change is: previously the bootstrap protos
had special logic for how they imported modules.  After this change
they can depend on them from proto-lens-runtime, just like other
generated protos.  This simplifies some logic in proto-lens-protoc.
Also update the bootstrap script.  It's mostly the same as before,
except that we first checkout an old version of the bootstrap proto
bindings that …
=> Move descriptor/plugin bindings to proto-lens-protobuf-types.

proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml, proto-lens-discrimination/package.yaml, proto-lens-optparse/Changelog.md, proto-lens-optparse/package.yaml, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-runtime/Changelog.md, proto-lens-runtime/package.yaml, proto-lens-setup/Changelog.md, proto-lens-setup/package.yaml, proto-lens/Changelog.md, proto-lens/package.yaml, travis-cabal.sh
Packages like proto-lens-optparse and proto-lens-arbitrary that
are compatible with the older versions only get a minor bump.
=> Bump the version to 0.6.

proto-lens-protobuf-types/package.yaml
This was preventing us from uploading the package to Hackage.
It was caused by #353 which (as expected) bumped the .cabal
file to require version 2.  Unfortunately, this ran afoul
of an hpack issue:
https://github.com/sol/hpack/issues/303
Specifically: (a) hpack auto-adds a `Paths_*`
module, and (b) Cabal v2 expects that to be listed explicitly
in `autogen-modules`, which hpack does not do.
Work around this by following a suggestion from the above thread:
include an explicit `verbatim`/`other-modules` clause,
which prevents hpack from auto-adding the `Paths_*` module.
=> Fix "cabal check" on proto-lens-protobuf-types.

proto-lens-protobuf-types/package.yaml, proto-lens-protobuf-types/src/Data/ProtoLens/Descriptor.hs, proto-lens-tests/tests/descriptor_test.hs, proto-lens/src/Data/ProtoLens/Message.hs
It contains the function `messageDescriptor` which is a nicer
API than `Data.ProtoLens.Message.packedMessageDescriptor`.
(We can't return a `DescriptorProto` directly in `Data.ProtoLens.Message`
because the `proto-lens` package doesn't have access to that type
yet (it's now exposed from proto-lens-protobuf-types).
=> Add Data.ProtoLens.Descriptor to proto-lens-protobuf-types.

proto-lens-arbitrary/package.yaml, proto-lens-discrimination/package.yaml, proto-lens-optparse/package.yaml, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-runtime/package.yaml, proto-lens-setup/package.yaml, proto-lens/Changelog.md, proto-lens/package.yaml
The new method `packedMessageDescriptor` is a breaking change
from the 0.6.* API.
I avoided doing the minor version bumps for other libraries;
we can do that when we do our next release (probably not for a bit).
Note: this is diffbased onto #362.
=> Update versions and changelogs for packagedMessageDescriptor

proto-lens-discrimination/package.yaml, proto-lens-discrimination/tests/disc_test.hs
If all three messages are equal, they'll get sorted into some arbitrary order, and the least won't be less than the greatest.  So, assert that either the least is less than the greatest, or all three are equal.
Note: I wasn't able to convince proto-lens to build in a few tens of minutes (all the .proto files in submodules were missing), so I gave up and decided to let the CI deal with it.  So, this might not even type-check yet.
=> Fix transitivity property test of message Sorts.  (#364)

proto-lens-protobuf-types/src/Data/ProtoLens/Descriptor.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-tests/tests/descriptor.proto, proto-lens-tests/tests/descriptor_test.hs, proto-lens/src/Data/ProtoLens/Message.hs
This change adds packedFileDescriptor to each Message as well as a
fileDescriptor helper function for getting the FileDescriptorProto
from this Message.
The FileDescriptorProto is required for reflectively understanding all
of the contents of a proto.  It's used, for example, by APIs that
persist protos.
While it may seem a little odd to have each Message defined in a proto
return the same FileDescriptorProto, this is about the third thing I
tried working with and found the alternatives to be much worse.
1. If `packedFileDescriptor` is exported from the module itself, much
code is broken due to duplicate definitions on flat imports.
2. Adding a new module, e.g. `MyProto_Descriptor` worked around the
issue at no cost by having the flat space separated.
However, both of these mean that an …
=> Add FileDescriptorProto to generated protos.

proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/enum_only.proto, proto-lens-tests/tests/enum_test.hs
Previously we got:
```
...../build/enum_test/autogen/Proto/EnumOnly.hs:72:1: error: [-Wunused-top-binds, -Werror=unused-top-binds]
Defined but not used: ‘packedFileDescriptor’
|
72 | packedFileDescriptor
| ^^^^^^^^^^^^^^^^^^^^
```
The check for whether the file had any messages was incorrect, since it didn't account for enums which are tracked in the same map.
=> Fix a warning when there are only enums, no messages.

proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/message_set.proto, proto-lens-tests/tests/message_set_test.hs, proto-lens/src/Data/ProtoLens/Encoding/Wire.hs
This can be enabled by adding "option message_set_wire_format = true" to
the proto message.
The encoding format is taken from C++ code
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wire_format.cc#L1046
=> Add support for message set wire format

proto-lens-protoc/package.yaml
I've verified that this compiles locally, but I haven't tested it as I didn't see any immediately obvious test suites that would exercise the `proto-lens-protoc` executable.
cf. commercialhaskell/stackage#5400
=> Relaxes ghc-source-gen upper bound

proto-lens-tests/package.yaml, proto-lens-tests/src/Data/ProtoLens/TestUtil.hs, proto-lens-tests/tests/any_test.hs, proto-lens-tests/tests/decode_delimited_test.hs, proto-lens-tests/tests/dependent_test.hs, proto-lens-tests/tests/descriptor_test.hs, proto-lens-tests/tests/enum_test.hs, proto-lens-tests/tests/imports_test.hs, proto-lens-tests/tests/labels_test.hs, proto-lens-tests/tests/message_set_test.hs, proto-lens-tests/tests/names_test.hs, proto-lens-tests/tests/no_package_test.hs, proto-lens-tests/tests/oneof_test.hs, proto-lens-tests/tests/optional_test.hs, proto-lens-tests/tests/package-deps_test.hs, proto-lens-tests/tests/proto3_test.hs, proto-lens-tests/tests/text_format_test.hs, proto-lens-tests/tests/unknown_fields_test.hs
Previously we switched from `test-framework` to `tasty`,
but continued to use `Test.HUnit` for simple assertion tests.
Unfortunately,  HUnit's exceptions don't get printed nicely by
`tasty`. For example, introducing an intentional bug in a test:
```
bytes:           FAIL
Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "proto-lens-tests-0.1.0.1-CZ6Ohah6nNGOHV46uMAQt", srcLocModule = "Data.ProtoLens.TestUtil", srcLocFile = "src/Data/ProtoLens/TestUtil.hs", srcLocStartLine = 93, srcLocStartCol = 5, srcLocEndLine = 93, srcLocEndCol = 48})) (ExpectedButGot Nothing "\"a: 151\"" "\"a: 150\"")
```
If we switch completely over to importing functions like `=@?`
from `Test.Tasty.HUnit` instead of `Test.HUnit`, we'll get
nicer exceptions like we did with `test-framework`.
```
bytes: …
```
=> Use tasty-hunit fully instead of HUnit.

proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs
`from` is a function name from ghc-source-gen now.
=> Fix name shadowing with ghc-source-gen 0.4.0.0

.travis.yml, README.md, proto-lens-runtime/package.yaml, proto-lens-tutorial/stack-nightly.yaml, proto-lens-tutorial/stack.yaml, travis-cabal-new.sh, travis-cabal.sh
And update the `reexported-modules` section of `proto-lens-runtime/package.yaml`. It changed from line-separated list to comma-separated list in the latest stack (hpack): https://github.com/sol/hpack/commit/c8a5d80238fe09b1ae56702ffb3b3305fd48bcd8.
=> Upgrade stack to v2.3.1.

bootstrap.hs, stack-bootstrap.yaml
Latest stack doesn't seem to support named commits such as 'master'.
Get the commit sha from `git rev-parse` and append it to the yaml file.
This doesn't fully fixx (intentional typo to make GitHub not close the issue) https://github.com/google/proto-lens/issues/391 but
goes one step further. We still get an error like:
```
$ stack runghc -- bootstrap.hs
Cloning 0bef8c2f3da645f068b8a26ac168c1da41608182 from https://github.com/google/proto-lens
Unsupported tarball from /tmp/with-repo-archive189930/foo.tar: Symbolic link dest not found from proto-lens/proto-lens-imports/google to ../../google/protobuf/src/google, looking for proto-lens/../google/protobuf/src/google.
This may indicate that the source is a git archive which uses git-annex.
See …
```
=> Use commit sha in stack-bootstrap.yaml

proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs
Some evidence of that redundancy:
```
> quickCheck (\(x :: Word64) -> (fromIntegral (x .|. 128) :: Word8) == (fromIntegral (x .&. 127 .|. 128) :: Word8))
+++ OK, passed 100 tests.
```
=> Remove redundant (.&. 127) from putVarInt

proto-lens/package.yaml
To fix the cabal build on CI, this PR relaxes the upper bound on the `profunctor` version from `< 5.6` to `< 6.0`.
This allows `proto-lens` to use the latest version of profunctor 5.6 (released on Oct 1).
Currently, `profunctor` is required by the following two dependencies, and cabal seems not to be able to resolve them correctly.
* `discrimination` requires `profunctor == 5.*.*`, cabal installs 5.6 (latest)
* `proto-lens` requires `profunctor >= 5.2 && < 5.6`, cabal installs 5.5.2
=> Fix cabal build on CI

README.md, docs/tutorial.md
This PR updates outdated descriptions and code examples in the tutorial:
* The module name for the package `microlens` is `Lens.Micro` and not `Microlens`.
* Some code examples assumed that `string` fields are represented with `String` in Haskell, while it is currently `Data.Text.Text`
* Type application needs a space before `@`; expressions like `field@"baz"` don't compile.
* Some examples were missing imports of `defMessage`, `(&)`, and `(.~)`
This PR also fixes some typos.
=> Update outdated docs and fix typos

.travis.yml, docs/installing-protoc.md, proto-lens-protoc/app/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor_Fields.hs, proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-tests/package.yaml, proto-lens-tests/tests/proto3_optional_test.hs, proto-lens-tests/tests/test_proto3_optional.proto
Fixes #380 following [instructions](https://github.com/protocolbuffers/protobuf/blob/e2cc2de/docs/implementing_proto3_presence.md) recommended in https://github.com/google/proto-lens/issues/380#issuecomment-619569960.
The main change here is to take the proto3 descriptor message but convert it to an internal representation more in line with what we'd generate for proto2. We treat the field as an `OptionalMaybeField` and drop the synthetic `oneof`. The serialization already works out of the box, since a `oneof` member is converted into an `OptionalMaybeField` as well.
For this to work, the descriptor proto needs to be updated to include the `FieldDescriptorProto.proto3_optional` field. We also need the `FEATURE_PROTO3_OPTIONAL` enum constant available so this plugin can tell `protoc` that …
=> Support proto3 optional

proto-lens-tests/tests/text_format.proto, proto-lens-tests/tests/text_format_test.hs, proto-lens/src/Data/ProtoLens/TextFormat.hs
I'm not sure the text format is exactly "standardized", but this is the set supported by the official C++ parser (see #410).
Fixes #410
=> Support all valid text format boolean field values

proto-lens-tests/tests/text_format_test.hs, proto-lens/src/Data/ProtoLens/TextFormat/Parser.hs
Parsing of UTF8 in string literals was broken.  See #418 
The current behavior is not 100% compatible with C++, but this at least expands the set of parseable messages.
=> Fixed parsing of UTF8 chars in text format proto string literals.

stack-9.0.yaml
- nightly resolver needs full name with date
- cassava is not a dependency of any of the packages, though an indirect
dependency. In any case, the removed cassava flag is not applicable because
nightly-2021-10-07 has bytestring-0.10.12.1.
- ghc-source-gen is in nightly-2021-10-07 so extra-deps is unnecessary
- allow-newer is unnecessary
=> Fixed stack-9.0.yaml

matrix.yaml, proto-lens-optparse/Changelog.md, proto-lens-optparse/package.yaml, proto-lens-optparse/proto-lens-optparse.cabal, stack-9.0.yaml, stack-9.2.yaml
The relevant yaml file no longer has to enumerate extra-deps.
=> Bump some bounds for ghc-9.2.2 compatibility

proto-lens-arbitrary/Changelog.md, proto-lens-arbitrary/package.yaml, proto-lens-arbitrary/proto-lens-arbitrary.cabal, proto-lens-discrimination/package.yaml, proto-lens-discrimination/proto-lens-discrimination.cabal, proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal, proto-lens-protoc/Changelog.md, proto-lens-protoc/package.yaml, proto-lens-protoc/proto-lens-protoc.cabal, proto-lens-runtime/Changelog.md, proto-lens-runtime/package.yaml, proto-lens-runtime/proto-lens-runtime.cabal, proto-lens-setup/Changelog.md, proto-lens-setup/package.yaml, proto-lens-setup/proto-lens-setup.cabal, proto-lens/Changelog.md, proto-lens/package.yaml, proto-lens/proto-lens.cabal
This was tested by using an explicit override with this diff:
```
--- a/stack-9.2.yaml
+++ b/stack-9.2.yaml
@@ -21,5 +21,10 @@ packages:
- proto-lens-tests
- proto-lens-tests-dep
+extra-deps:
+  - text-2.0
+  - Cabal-3.6.3.0@sha256:ff97c442b0c679c1c9876acd15f73ac4f602b973c45bde42b43ec28265ee48f4,12459
+  - parsec-3.1.15.0@sha256:a162d4cc8884014ba35192545cad293af0529fe11497aad8834bbaaa3dfffc26,4429
+
ghc-options:
"$locals": -Wall -Werror
```
=> Relax text bounds to allow text-2.0

proto-lens-protobuf-types/Changelog.md, proto-lens-protobuf-types/package.yaml, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal
Minor tweaks to its package.yaml to work with newer hpack-0.35.
=> Release proto-lens-protobuf-types-0.7.1.2

.github/workflows/cabal-ci.yml, ghc94.cabal.project, proto-lens-runtime/package.yaml, proto-lens-runtime/proto-lens-runtime.cabal, proto-lens/package.yaml, proto-lens/proto-lens.cabal, proto-lens/src/Data/ProtoLens/Combinators.hs
With a little subsumption related change, `proto-lens` can be made to work with GHC 9.4.
Other packages have dependency trees that don't support GHC 9.4 yet, so I deliberately made this PR small to just add support to these two packages mentioned in the title.
Tested using
cabal test -w ghc-9.4.1 --constraint='vector>=0.13'
=> Allow GHC 9.4 (and CI) for `proto-lens` and `proto-lens-runtime`

.gitignore, proto-lens-benchmarks/benchmarks/LargeFields.hs, proto-lens-benchmarks/benchmarks/large_fields.proto, proto-lens-benchmarks/package.yaml, proto-lens-benchmarks/proto-lens-benchmarks.cabal, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate/Field.hs, proto-lens/src/Data/ProtoLens/Encoding/Bytes.hs, proto-lens/src/Data/ProtoLens/Encoding/Parser.hs
I noticed a performance issue while I was decoding a large text. After profiling, I found the procedure of the current implementation for the paring string field seems inefficient, especially for a large string.
There are two steps for parsing string(text):
```
getText: getBytes -> decodeUtf8
```
And `getBytes` will call `packCStringLen` to copy the ByteString which seems redundant since `decodeUtf8` also makes a copy.
```
benchmarking 10K(10kB)/encode
time                 4.486 μs   (4.472 μs .. 4.498 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 4.479 μs   (4.467 μs .. 4.493 μs)
std dev              45.67 ns   (35.00 ns .. 62.79 ns)
benchmarking 10K(10kB)/decode/whnf
time                 2.115 μs   (2.109 μs .. 2.124 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean …
```
=> optimize decoding time of string field

proto-lens/package.yaml, proto-lens/proto-lens.cabal
Tested using
cabal test --constraint='transformers>=0.6' -w ghc-9.4.3
=> Support transformers-0.6 series

.github/workflows/cabal-ci.yml, ghc96.cabal.project, proto-lens-optparse/package.yaml, proto-lens-optparse/proto-lens-optparse.cabal, proto-lens-runtime/package.yaml, proto-lens-runtime/proto-lens-runtime.cabal, proto-lens/package.yaml, proto-lens/proto-lens.cabal
This adds cabal testing for the optparse package, since it doesn't depend on the codegen that doesn't work on GHC 9.2+ yet.
=> Allow ghc-9.6

.github/workflows/stack-ci.yml
Closes #453 
Update `.github/workflows/stack-ci.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=ci-builds::$CI_BUILDS"
```
**TO-BE**
```yaml
echo "ci-builds=$CI_BUILDS" >> $GITHUB_OUTPUT
```
=> Replace deprecated command with environment file

proto-lens-protobuf-types/package.yaml, proto-lens-protobuf-types/proto-lens-protobuf-types.cabal
Some well known types with message definitions in Protobuf source code were not being converted into Haskell. Proto definitions that depend on those types (e.g., FieldMask) failed to build. This PR adds those types to the auto-generated code so proto definitions that depend on them can build.
There is an open PR (#455) that overlaps with this one. However, that PR has been asked to remove the changes that overlap with this one. This PR simply adds to the existing `Setup.hs` approach.
=> Add support for additional well known types

.gitmodules, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Compiler/Plugin_Fields.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor.hs, proto-lens-protoc/app/Proto/Google/Protobuf/Descriptor_Fields.hs, stack-bootstrap.yaml
* Update location to the current one at https://github.com/protocolbuffers/protobuf
* Update `protobuf` submodule to v28.0
* Regenerate bootstrapping protobuf bindings with `runghc bootstrap.hs`
This is preparatory work for supporting Protobuf Editions (issue #468), which requires the updates to the protocol buffer message types defined for `protoc` plugins.
=> Catch up on changes in protobuf up to v28.0.

.github/workflows/stack-ci.yml
We will need to use a much more recent version of `protoc` if we wish to test Protobuf Editions files.  Old `protoc` versions will not be able to parse new syntax.  For example, a newer version is required for the tests in https://github.com/chungyc/proto-lens/pull/8 to pass.
=> Check out protoc v28.x during Stack continuous integration.

.github/dependabot.yml
The GitHub actions used by proto-lens are becoming years out of date.  We should let automation handle preparing updates, even if approval remains manual.
Also use grouping to reduce the number of pull requests.
=> Set up Dependabot.

.github/workflows/hlint.yml, .hlint.yaml
Adds a code scanning workflow using HLint.  Suggestions and warnings are included inline for pull requests and the code scanning dashboard in the security tab.  See https://github.com/haskell-actions/hlint-scan#examples for an example.
This sets up HLint to ignore warnings that would be triggered by the existing code.  We would likely want to enable some of them, for example, `Redundant $` to remove unnecessary `$` operators.  Others could be marked as permanently disabled.  This could be done in future changes.
Resolves #279.
=> Add HLint workflow.

proto-lens-protoc/app/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Editions/Features.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Plugin.hs, proto-lens-protoc/app/protoc-gen-haskell.hs
This basically replaces `SyntaxType` distinguishing between proto2 and proto3 with `FeatureSet` controlling individual features in Protobuf Editions.  For example, instead of checking whether the syntax is proto3 when determining whether repeated fields should use packed encoding by default, we check whether `features.repeated_field_encoding` is `PACKED`.  The default feature set [compatible with proto2 and proto3](https://protobuf.dev/editions/features/#preserving) are provided by `protoc` and included in `Data.ProtoLens.Compiler.Defaults`.  The existing tests continue to pass, showing that the features have been determined correctly.
This does not complete support for Protobuf Editions.  This requires the ability to override options in certain scopes, e.g., file scope or field scope, …
=> Use per-edition feature defaults instead of syntax type to control behavior.

README.md, proto-lens-protoc/app/Data/ProtoLens/Compiler/Definitions.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Editions/Defaults.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate/Encoding.hs, proto-lens-protoc/app/protoc-gen-haskell.hs, proto-lens-tests/package.yaml, proto-lens-tests/proto-lens-tests.cabal, proto-lens-tests/tests/edition2023.proto, proto-lens-tests/tests/edition2023_fileoptions.proto, proto-lens-tests/tests/edition2023_test.hs
This completes support of Protobuf Editions to the same level that proto-lens supports proto2 and proto3 except for the following, which I do not think are critical bugs:
* `features.utf8_validation = NONE` does not disable UTF-8 validation.
* If more than one field sharing the same message type are in a single message type, and if one of the fields has `features.message_encoding = DELIMITED`, then all of these fields will use `DELIMITED` encoding.
Unevaluated tests are intentionally included despite warnings by HLint so that they are still built and can be easily enabled later if the above are fixed.
Resolves https://github.com/google/proto-lens/issues/468.
=> Override features defined in enclosed scopes.

README.md
The broken build status badge has been bothering me for a while.
=> Update build status badge to Cabal build status.

.hlint.yaml, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate.hs, proto-lens-protoc/app/Data/ProtoLens/Compiler/Generate/Commented.hs, proto-lens-setup/src/Data/ProtoLens/Setup.hs, proto-lens-tests/tests/decode_delimited_test.hs, proto-lens-tests/tests/proto3_optional_test.hs
The specific hints that are enabled are `Fuse foldr/map`, `Use :`, `Use camelCase`, `Use concatMap`, `Use maybe`, `Use newtype instead of data`, and `Use replicate`.
These are the last of the hints I will be enabling, which seem uncontroversial enough.  The rest range from those that I am ambivalent about (e.g., `Eta reduce`; point-free style is fine, but I don't feel that we need to strive to be point-free as much as possible) to those I think are a bad idea (e.g., `Use <$`; it's a generally obscure enough operator that isn't used enough in this code base for it to become naturally familiar with).
=> Enable more hints for HLint.

.github/workflows/cabal-ci.yml, .github/workflows/stack-ci.yml
haskell/actions/setup is deprecated because it ran afoul of the best practice of having only one action per repository.  See https://github.com/haskell/actions.
=> Switch from haskell/actions/setup to haskell-actions/setup.

proto-lens-protoc/app/Data/ProtoLens/Compiler/Editions/Defaults.hs, proto-lens-protoc/app/protoc-gen-haskell.hs
Protobuf Editions 2024 has [no new generic features](https://github.com/protocolbuffers/protobuf/blob/15487415e4077066d5ebdd4357d045cfaa1771b2/src/google/protobuf/descriptor.proto#L964-L1087), so there is no reason not to accept such files for Haskell.  Editions 2024 is useful for specifying the introduction of language-specific features, and non-Haskell features are not useful to us.
=> Expand support to Protobuf Editions 2024.

ghc9.10.1.cabal.project
This fixes the broken build of master:
https://github.com/google/proto-lens/actions/runs/12943350675/job/36173525348
=> Remove ghc-source-gen pin and include the tests into the plan

.github/workflows/stack-ci.yml
`arduino/setup-protoc` uses the GitHub API to fetch release data.  Unauthenticated requests have a much lower rate limit, so pass on the GitHub token so that it can issue authenticated requests. Unauthenticated requests with the lower rate limit may cause builds to fail.
Explicitly set the permissions to be read-only, since the workflow does not need write access to the repository, so that accidental or malicious changes cannot be made despite having the authentication token.
* Failed workflow: https://github.com/google/proto-lens/actions/runs/13092278602/job/36530330732?pr=502.
* Suggestion by `arduino/setup-protoc` to include the token: https://github.com/arduino/setup-protoc#usage
=> Include GitHub authentication token while setting up protoc.
